(define (problem prob32) (:domain peticionador)
(:objects
    r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 - rover
    b2 - almacen
    b0 b1 - asentamiento
    p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 - peticion
)
(:init
    (= (peticiones-cerradas) 0)
    (camino b0 b1)
    (camino b0 b2)
    (camino b1 b2)
    (= (suministros-base b2) 3)
    (= (suministros-base b0) 0)
    (= (suministros-base b1) 0)
    (= (personal-base b0) 0)
    (= (personal-base b1) 0)
    (= (personal-base b2) 0)
    (= (suministros-rover r0) 0) (= (personal-rover r0) 0) (estacionado r0 b2)
    (= (suministros-rover r1) 0) (= (personal-rover r1) 0) (estacionado r1 b3)
    (= (suministros-rover r2) 0) (= (personal-rover r2) 0) (estacionado r2 b2)
    (= (suministros-rover r3) 0) (= (personal-rover r3) 0) (estacionado r3 b1)
    (= (suministros-rover r4) 0) (= (personal-rover r4) 0) (estacionado r4 b1)
    (= (suministros-rover r5) 0) (= (personal-rover r5) 0) (estacionado r5 b2)
    (= (suministros-rover r6) 0) (= (personal-rover r6) 0) (estacionado r6 b1)
    (= (suministros-rover r7) 0) (= (personal-rover r7) 0) (estacionado r7 b0)
    (= (suministros-rover r8) 0) (= (personal-rover r8) 0) (estacionado r8 b2)
    (= (suministros-rover r9) 0) (= (personal-rover r9) 0) (estacionado r9 b1)
    (peticion-abierta p0 b1) (peticion-suministros p0)
    (peticion-abierta p1 b0) (peticion-suministros p1)
    (peticion-abierta p2 b0) (peticion-suministros p2)
    (peticion-abierta p3 b1) (peticion-suministros p3)
    (peticion-abierta p4 b1) (peticion-personal p4)
    (peticion-abierta p5 b0) (peticion-personal p5)
    (peticion-abierta p6 b1) (peticion-personal p6)
    (peticion-abierta p7 b1) (peticion-personal p7)
    (peticion-abierta p8 b1) (peticion-personal p8)
    (peticion-abierta p9 b0) (peticion-personal p9)
    (peticion-abierta p10 b1) (peticion-personal p10)
    (peticion-abierta p11 b1) (peticion-personal p11)
    (peticion-abierta p12 b1) (peticion-personal p12)
    (peticion-abierta p13 b0) (peticion-personal p13)
    (peticion-abierta p14 b0) (peticion-personal p14)
    (peticion-abierta p15 b0) (peticion-personal p15)
    (peticion-abierta p16 b1) (peticion-personal p16)
    (peticion-abierta p17 b0) (peticion-personal p17)
    (peticion-abierta p18 b1) (peticion-personal p18)
    (peticion-abierta p19 b1) (peticion-personal p19)
    (peticion-abierta p20 b0) (peticion-personal p20)
    (peticion-abierta p21 b1) (peticion-personal p21)
    (peticion-abierta p22 b0) (peticion-personal p22)
    (peticion-abierta p23 b0) (peticion-personal p23)
    (peticion-abierta p24 b0) (peticion-personal p24)
    (peticion-abierta p25 b0) (peticion-personal p25)
    (peticion-abierta p26 b0) (peticion-personal p26)
    (peticion-abierta p27 b1) (peticion-personal p27)
    (peticion-abierta p28 b0) (peticion-personal p28)
    (peticion-abierta p29 b0) (peticion-personal p29)
    (peticion-abierta p30 b1) (peticion-personal p30)
    (peticion-abierta p31 b1) (peticion-personal p31)
)
(:goal
    (= (peticiones-cerradas) 3)
)
)