(define (problem prob16) (:domain peticionador)
(:objects
    r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 - rover
    b2 b3 b5 b7 b8 b12 b15 - almacen
    b0 b1 b4 b6 b9 b10 b11 b13 b14 - asentamiento
    p0 p1 p2 - peticion
)
(:init
    (= (peticiones-cerradas) 0)
    (camino b0 b1)
    (camino b0 b15)
    (camino b1 b2)
    (camino b2 b8)
    (camino b3 b4)
    (camino b3 b7)
    (camino b3 b9)
    (camino b3 b13)
    (camino b4 b9)
    (camino b4 b6)
    (camino b5 b6)
    (camino b8 b9)
    (camino b10 b11)
    (camino b10 b14)
    (camino b11 b12)
    (camino b12 b13)
    (= (suministros-base b2) 1)
    (= (suministros-base b3) 0)
    (= (suministros-base b5) 0)
    (= (suministros-base b7) 0)
    (= (suministros-base b8) 0)
    (= (suministros-base b12) 0)
    (= (suministros-base b15) 0)
    (= (suministros-base b0) 0)
    (= (suministros-base b1) 0)
    (= (suministros-base b4) 0)
    (= (suministros-base b6) 0)
    (= (suministros-base b9) 0)
    (= (suministros-base b10) 0)
    (= (suministros-base b11) 0)
    (= (suministros-base b13) 0)
    (= (suministros-base b14) 0)
    (= (personal-base b0) 1)
    (= (personal-base b1) 0)
    (= (personal-base b4) 1)
    (= (personal-base b6) 0)
    (= (personal-base b9) 0)
    (= (personal-base b10) 0)
    (= (personal-base b11) 0)
    (= (personal-base b13) 0)
    (= (personal-base b14) 0)
    (= (personal-base b2) 0)
    (= (personal-base b3) 0)
    (= (personal-base b5) 0)
    (= (personal-base b7) 0)
    (= (personal-base b8) 0)
    (= (personal-base b12) 0)
    (= (personal-base b15) 0)
    (= (suministros-rover r0) 0) (= (personal-rover r0) 0) (estacionado r0 b10)
    (= (suministros-rover r1) 0) (= (personal-rover r1) 0) (estacionado r1 b15)
    (= (suministros-rover r2) 0) (= (personal-rover r2) 0) (estacionado r2 b3)
    (= (suministros-rover r3) 0) (= (personal-rover r3) 0) (estacionado r3 b11)
    (= (suministros-rover r4) 0) (= (personal-rover r4) 0) (estacionado r4 b13)
    (= (suministros-rover r5) 0) (= (personal-rover r5) 0) (estacionado r5 b10)
    (= (suministros-rover r6) 0) (= (personal-rover r6) 0) (estacionado r6 b6)
    (= (suministros-rover r7) 0) (= (personal-rover r7) 0) (estacionado r7 b15)
    (= (suministros-rover r8) 0) (= (personal-rover r8) 0) (estacionado r8 b14)
    (= (suministros-rover r9) 0) (= (personal-rover r9) 0) (estacionado r9 b16)
    (peticion-abierta p0 b9) (peticion-suministros p0)
    (peticion-abierta p1 b0) (peticion-personal p1)
    (peticion-abierta p2 b14) (peticion-personal p2)
)
(:goal
    (= (peticiones-cerradas) 3)
)
)